Adjust carrer path
loadsmart/culture pull request #66
Opened 2024-05-02 21:06 UTC by gillianomenezes

## Description

Adjust career path names to follow the guidelines available here: https://loadsmart.atlassian.net/wiki/spaces/engineering/pages/3685122185/Career+Levels

2024-05-02 21:08 UTC, rcmachado commented
@gillianomenezes We also don't have the `I`, `II` suffixes anymore.

2024-05-02 23:05 UTC, ellisonleao approved these changes

2024-05-03 14:01 UTC, cristianowa commented on careers/career-path.md
>  - Engineer II
```suggestion
- Engineer II
```

2024-05-06 12:46 UTC, rcmachado requested changes
Please adjust `I` and `II` suffixes, as they don't exist anymore.

Also, the confluence link is private -- so it won't provide much information to people outside Loadsmart.

2024-05-06 13:50 UTC, rcmachado approved these changes

2025-01-16 18:20 UTC, closed without merging